#!/usr/bin/env bash

## Usage:
## suppose project root dir is xxx
## edit config.yml first
#> mamba activate ngs
#> bash run_cuttag.sh config.yml 
## edit xxx/samplesheet.csv (generated by previous commond)
#> bash run_cuttag.sh config.yml

set -euo pipefail

# Fail fast if no config provided
if [[ ${#@} -lt 1 ]]; then
    echo "Usage: $0 config.yml" >&2
    exit 1
fi

# ============================= Helper Functions =============================
# Get script directory (works with symlinks)
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"

# Helper functions are located in the parent directory
HELPER_SCRIPT="${SCRIPT_DIR}/../helper.sh"
if [[ ! -f "$HELPER_SCRIPT" ]]; then
    echo "ERROR: Helper script not found: $HELPER_SCRIPT" >&2
    exit 1
fi
source "$HELPER_SCRIPT"

# ============================= Configuration Loading =============================
parse_yaml_config() {
    local config="$1"
    
    # Simple YAML parser (handles key: value pairs)
    # -g so CUSTOM_BED_REGIONS survives function return and is consumed in main()
    declare -ga CUSTOM_BED_REGIONS=()
    while IFS=': ' read -r key value || [[ -n "$key" ]]; do
        # Skip comments and empty lines
        [[ "$key" =~ ^[[:space:]]*# ]] && continue
        [[ -z "$key" ]] && continue
        
        # Remove leading/trailing whitespace and quotes
        key=$(echo "$key" | xargs)
        value=$(echo "$value" | xargs | sed 's/^["'\'']\|["'\'']$//g')
        
        # Skip empty values
        [[ -z "$value" ]] && continue
        
        # Map config keys to variables
        case "$key" in
            root_dir) ROOT_DIR="$value";;
            species) SPECIES="$value" ;;
            fastq_dir) FASTQ_DIR="$value" ;;
            samplesheet) SAMPLESHEET="$value" ;;
            outdir) OUTDIR="$value" ;;
            threads) THREADS="$value" ;;
            skip_preprocess) SKIP_PREPROCESS="$value" ;;
            sort_mem_limit) SORT_MEM_LIMIT="$value" ;;
            max_frag_length) MAX_FRAG_LENGTH="$value" ;;
            peak_caller) PEAK_CALLER="$value" ;;
            macs_parameter) MACS_PARAMETER="$value" ;;
            seacr_parameter) SEACR_PARAMETER="$value" ;;
            run_spike) RUN_SPIKE="$value" ;;
            norm_method) NORM_METHOD="$value" ;;
            heatmap_binsize) HEATMAP_BINSIZE="$value" ;;
            heatmap_max_regions) HEATMAP_MAX_REGIONS="$value" ;;
            pca_ntop) PCA_NTOP="$value" ;;
            index_rootdir) INDEX_ROOTDIR="$value" ;;
            spike_free_sf_file) SPIKE_FREE_SF_FILE="$value" ;;
            bed_region) 
                # Add custom BED regions to array
                if [[ -f "$value" ]]; then
                    CUSTOM_BED_REGIONS+=("$value")
                    log_info "Added custom BED region: $value"
                else
                    log_warn "Custom BED file not found: $value, skipped"
                fi
                ;;
        esac
    done < <(tr -d '\r' < "$config")

    # Peak file extension used by MACS3: broad -> broadPeak, otherwise narrowPeak
    if [[ "$MACS_PARAMETER" =~ --broad ]]; then
        PEAK_EXT="_peaks.broadPeak"
    else
        PEAK_EXT="_peaks.narrowPeak"
    fi
} 


# ============================= Sample Processing Functions =============================
bowtie2_alignment() {
    local sample="$1"
    local clean1="$FASTP_DIR/${sample}_R1.fq.gz"
    local clean2="$FASTP_DIR/${sample}_R2.fq.gz"
    
    local sorted_bam="$ALIGN_DIR/${sample}.sorted.bam"
    local markdup_bam="$ALIGN_DIR/${sample}.markdup.bam"
    local flagstat_file="$ALIGN_DIR/${sample}.markdup.flagstat"
    
    if [[ ! -s "$markdup_bam" || ! -s "${markdup_bam}.bai" ]]; then
        log_info "[$sample] Aligning to genome"
        bowtie2 -x "$BOWTIE2_INDEX" -1 "$clean1" -2 "$clean2" -p "$THREADS" --phred33 \
            --very-sensitive --local --no-mixed --no-discordant -I 10 -X "$MAX_FRAG_LENGTH" \
            --rg-id "$sample" --rg "SM:${sample}\tPL:ILLUMINA" \
            2>"$ALIGN_DIR/${sample}.bowtie2.log" \
            | sambamba view -t "$THREADS" -S -f bam /dev/stdin 2>/dev/null \
            | sambamba sort -t "$THREADS" -m "$SORT_MEM_LIMIT" -o "$sorted_bam" /dev/stdin 2>/dev/null
        
        log_info "[$sample] Marking duplicates"
        sambamba markdup -t "$THREADS" "$sorted_bam" "$markdup_bam" 2>/dev/null
        sambamba index -t "$THREADS" "$markdup_bam" 2>/dev/null
        sambamba flagstat "$markdup_bam" > "$flagstat_file" 2>/dev/null
        [[ "$(wc -c < ${flagstat_file})" -gt 5 ]] && rm "$sorted_bam" "${sorted_bam}.bai"
    fi
    
    # Extract statistics
    local total_reads=$(extract_flagstat_value "$flagstat_file" "in total" 1)
    local mapped_reads=$(extract_flagstat_value "$flagstat_file" "mapped (.*N/A)" 1)
    local duplicate_reads=$(extract_flagstat_value "$flagstat_file" "duplicates" 1)
    
    echo "$total_reads $mapped_reads $duplicate_reads"
}

bowtie2_alignment_spike() {
    local sample="$1"
    local clean1="$FASTP_DIR/${sample}_R1.fq.gz"
    local clean2="$FASTP_DIR/${sample}_R2.fq.gz"
    
    local spike_sorted_bam="$ALIGN_DIR/${sample}.spike.sorted.bam"
    local spike_flagstat="$ALIGN_DIR/${sample}.spike.sorted.flagstat"
    
    if [[ ! -s "$spike_flagstat" ]]; then
        log_info "[$sample] Aligning to spike-in genome"
        bowtie2 -x "$SPIKE_INDEX" -1 "$clean1" -2 "$clean2" -p "$THREADS" --phred33 \
            --very-sensitive --local --no-mixed --no-discordant -I 10 -X "$MAX_FRAG_LENGTH" \
            --rg-id "$sample" --rg "SM:${sample}\tPL:ILLUMINA" \
            2>"$ALIGN_DIR/${sample}.spike.bowtie2.log" \
            | sambamba view -t "$THREADS" -S -f bam /dev/stdin 2>/dev/null \
            | sambamba sort -t "$THREADS" -m "$SORT_MEM_LIMIT" \
                -o "$spike_sorted_bam" /dev/stdin 2>/dev/null
        
        sambamba flagstat "$spike_sorted_bam" > "$spike_flagstat" 2>/dev/null
        [[ "$(wc -c < ${spike_flagstat})" -gt 5 ]] && rm "$spike_sorted_bam" "${spike_sorted_bam}.bai"
    fi
    
    local spike_reads=$(extract_flagstat_value "$spike_flagstat" "mapped (.*N/A)" 1)
    echo "$spike_reads"
}

bam_filter() {
    local sample="$1"
    local markdup_bam="$ALIGN_DIR/${sample}.markdup.bam"
    local filtered_bam="$ALIGN_DIR/${sample}.filtered.bam"
    local flagstat_filtered="$ALIGN_DIR/${sample}.filtered.flagstat"
    
    if [[ ! -s "$flagstat_filtered" ]]; then
        local chr_filter
        case "$SPECIES" in
            chm13|hs|mm)
                chr_filter='rname =~ "^chr([0-9]+|X|Y)$"'
                ;;
            cel)
                chr_filter='rname =~ "^(I|II|III|IV|V|X)$"'
                ;;
            fly)
                chr_filter='rname =~ "^(2[LR]|3[LR]|4|X|Y)$"'
                ;;
        esac
        if [[ -z "${chr_filter:-}" ]]; then
            log_error "[$sample] Unsupported species '$SPECIES' in bam_filter (supported: chm13, hs, mm, cel, fly)"
            exit 1
        fi
        log_info "[$sample] Filtering BAM (MAPQ≥30, proper pairs, main chromosomes)"
        samtools view -@ "$THREADS" -b -f 2 -q 30 -F 1804 \
            -e "$chr_filter" \
            -o "$filtered_bam" "$markdup_bam"
        sambamba index -t "$THREADS" "$filtered_bam" 2>/dev/null
        sambamba flagstat -t "$THREADS" "$filtered_bam" > "$flagstat_filtered" 2>/dev/null
    fi
    
    local filtered_reads=$(extract_flagstat_value "$flagstat_filtered" "mapped (.*N/A)" 1)
    echo "$filtered_reads"
}

generate_bigwig() {
    local sample="$1" scale_factor="$2"
    local filtered_bam="$ALIGN_DIR/${sample}.filtered.bam"
    local bigwig="$ALIGN_DIR/${sample}.${NORM_METHOD}.bw"
    
    if [[ ! -s "$bigwig" ]]; then
        log_info "[$sample] Generating BigWig (scale: $scale_factor)"
        bamCoverage -b "$filtered_bam" -o "$bigwig" \
            -p "$THREADS" --binSize 10 --scaleFactor "$scale_factor" 2>/dev/null
    fi
}


run_alignment() {
    local sample="$1" group="$2" control="$3" target="$4" fq1="$5" fq2="$6"
    
    # Skip if already processed
    if grep -q "^${sample}," "$STATS_CSV"; then
        log_info "[$sample] Alignment completed"
        return 0
    fi
    
    # Alignment and marking duplicates
    read total_reads mapped_reads duplicate_reads <<< $(bowtie2_alignment "$sample")
    local mapped_pct dup_pct
    mapped_pct=$(awk -v m="$mapped_reads" -v t="$total_reads" 'BEGIN{if(t==0){printf "0.00"} else {printf "%.2f", (m/t)*100}}')
    dup_pct=$(awk -v d="$duplicate_reads" -v t="$total_reads" 'BEGIN{if(t==0){printf "0.00"} else {printf "%.2f", (d/t)*100}}')
    log_info "[$sample] Stats - Total: $total_reads, Mapped: $mapped_reads (${mapped_pct}%), Duplicates: $duplicate_reads (${dup_pct}%)"
    
    # Filtering
    local filtered_reads=$(bam_filter "$sample")
    filtered_pct=$(awk -v d="$filtered_reads" -v t="$total_reads" 'BEGIN{if(t==0){printf "0.00"} else {printf "%.f", (d/t)*100}}')
    log_info "[$sample] Filtered reads: $filtered_reads (${filtered_pct}%)"

    # Spike-in alignment (optional)
    local spike_reads=0
    if [[ "$RUN_SPIKE" == true ]]; then
        spike_reads=$(bowtie2_alignment_spike "$sample")
        spike_pct=$(awk -v d="$spike_reads" -v t="$total_reads" 'BEGIN{if(t==0){printf "0.000"} else {printf "%.3f", (d/t)*100}}')
        log_info "[$sample] Spike-in reads: $spike_reads (${spike_pct}%)"
    fi
    
    # Calculate normalization scale factor
    local spike_free_file
    if [[ -n "${SPIKE_FREE_SF_FILE:-}" ]]; then
        spike_free_file="$SPIKE_FREE_SF_FILE"
        [[ "$spike_free_file" != /* ]] && spike_free_file="$ROOT_DIR/$spike_free_file"
    else
        spike_free_file="$ALIGN_DIR/SpikeFree_SF.txt"
    fi
    local scale_factor
    scale_factor=$(calculate_scale_factor "$NORM_METHOD" "$filtered_reads" "$spike_reads" "$sample" "$spike_free_file")
    log_info "[$sample] Normalization: $NORM_METHOD, Scale factor: $scale_factor"
    
    # Generate BigWig
    generate_bigwig "$sample" "$scale_factor"
    
    # Append to statistics (FRiP is written per-tool during peak QC:
    # 04_peaks/<tool>/consensus_<target>_frip.tab via plotEnrichment)
    printf '%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n' \
        "$sample" "$group" "$control" "$target" "$fq1" "$fq2" \
        "$total_reads" "$mapped_reads" "$duplicate_reads" "$filtered_reads" \
        "$spike_reads" "$NORM_METHOD" "$scale_factor" >> "$STATS_CSV"
}

# ============================= Peak Calling =============================
# Find the peak file produced by a caller for a given sample.
# Usage: discover_peak_file <tool> <sample> <tool_peak_dir> [stringency]
# Safe under `set -euo pipefail`: never relies on a failing `ls` pipeline and
# always returns 0 (empty string when no peak file exists yet).
discover_peak_file() {
    local tool="$1" sample="$2" peak_dir="$3"
    local -a globs=()
    case "$tool" in
        macs)
            globs=("$peak_dir"/${sample}*_peaks.*Peak) ;;
        seacr)
            # Prefer the peak matching the current config stringency when
            # several (.relaxed/.stringent) files coexist from previous runs
            local pref=""
            [[ -n "${4:-}" ]] && pref=".${4}"
            globs=("$peak_dir"/${sample}${pref}.bed "$peak_dir"/${sample}.*.bed)
            ;;
    esac
    local f
    for f in "${globs[@]}"; do
        [[ -f "$f" ]] && { echo "$f"; return 0; }
    done
    return 0
}

run_macs() {
    local sample="$1" group="$2" control="$3" target="$4"
    
    local filtered_bam="$ALIGN_DIR/${sample}.filtered.bam"
    local peak_file="$TOOL_PEAK_DIR/${sample}${PEAK_EXT}"
    
    if [[ ! -s "$peak_file" ]]; then
        log_info "[$sample] Running macs"
        
        # Build MACS3 arguments
        local -a macs_args=("-t" "$filtered_bam" "-f" "BAMPE" "-g" "$GSIZE" "-n" "$TOOL_PEAK_DIR/${sample}" "--keep-dup" "all")
        # Split MACS parameters string into array and append
        read -ra macs_params_arr <<< "$MACS_PARAMETER"
        macs_args+=("${macs_params_arr[@]}")
        
        if [[ -n "$control" ]]; then
            local control_bam="$ALIGN_DIR/${control}.filtered.bam"
            if [[ -f "$control_bam" ]]; then
                macs_args+=("-c" "$control_bam")
            else
                log_warn "[$sample] Control BAM not found: $control_bam"
            fi
        fi
        
        macs3 callpeak "${macs_args[@]}" 2>/dev/null || \
            log_warn "[$sample] macs3 callpeak failed"
        # Remove bulky intermediate; keep xls/summits as small useful outputs
        rm -f "$TOOL_PEAK_DIR/${sample}_control_lambda.bdg"
    else
        log_info "[$sample] Call peak completed"
    fi
}

run_seacr() {
    local sample="$1" group="$2" control="$3" target="$4"
    
    # Parse positional SEACR args: <threshold> <norm|non> <relaxed|stringent>
    read -ra seacr_params_arr <<< "$SEACR_PARAMETER"
    local threshold="${seacr_params_arr[0]:-0.01}"
    local norm_mode="${seacr_params_arr[1]:-non}"
    local stringency="${seacr_params_arr[2]:-stringent}"
    
    local peak_file="$TOOL_PEAK_DIR/${sample}.${stringency}.bed"
    if [[ -s "$peak_file" ]]; then
        log_info "[$sample] SEACR peak completed"
        return 0
    fi
    
    # SEACR needs 4-column bedgraph input derived from the filtered BAM.
    # Generated with deepTools bamCoverage (multi-threaded, raw counts;
    # equivalent signal to `bedtools genomecov -bg` but much faster).
    local tempdir="$TOOL_PEAK_DIR/.tmp_bg"
    mkdir -p "$tempdir"
    # Drop stale bedgraphs (e.g. from an aborted run with a different generator)
    rm -f "$tempdir"/*.bg* 2>/dev/null
    local exp_bg="$tempdir/${sample}.bg"
    local exp_tmp="$tempdir/${sample}.bg.tmp"
    if [[ ! -s "$exp_bg" ]]; then
        bamCoverage -b "$ALIGN_DIR/${sample}.filtered.bam" -o "$exp_tmp" \
            --outFileFormat bedgraph --binSize 1 \
            -p "$THREADS" --minMappingQuality 0 2>/dev/null && \
            mv -f "$exp_tmp" "$exp_bg" || {
                log_warn "[$sample] bamCoverage failed, skipping SEACR for this sample"
                rm -f "$exp_tmp"
                return 0
            }
    fi
    [[ -s "$exp_bg" ]] || {
        log_warn "[$sample] empty bedgraph, skipping SEACR for this sample"
        return 0
    }
    
    local -a seacr_args=("$exp_bg")
    local ctrl_bg=""
    if [[ -n "$control" ]]; then
        ctrl_bg="$tempdir/${control}.bg"
        if [[ ! -s "$ctrl_bg" ]]; then
            local ctrl_tmp="$tempdir/${control}.bg.tmp"
            bamCoverage -b "$ALIGN_DIR/${control}.filtered.bam" -o "$ctrl_tmp" \
                --outFileFormat bedgraph --binSize 1 \
                -p "$THREADS" --minMappingQuality 0 2>/dev/null && \
                mv -f "$ctrl_tmp" "$ctrl_bg" || {
                    log_warn "[$sample] bamCoverage failed for control: $control"
                    rm -f "$ctrl_tmp"
                    ctrl_bg=""
                }
        fi
        if [[ -s "$ctrl_bg" ]]; then
            seacr_args+=("$ctrl_bg")
        else
            log_warn "[$sample] Control bedgraph not generated for: $control"
        fi
    fi
    # No control -> use the numeric threshold from SEACR_PARAMETER
    if [[ ${#seacr_args[@]} -eq 1 ]]; then
        seacr_args+=("$threshold")
    fi
    seacr_args+=("$norm_mode" "$stringency" "$TOOL_PEAK_DIR/${sample}")
    
    log_info "[$sample] Running SEACR"
    ( cd "$tempdir" && SEACR_1.3.sh "${seacr_args[@]}" ) || \
        log_warn "[$sample] SEACR failed"
    
    # Cleanup temp bedgraphs. NOTE: this must be the function exit path with
    # status 0 — a `[[ -n $x ]] && rm ...` ending would return 1 for no-control
    # samples and silently abort the whole pipeline under `set -e`.
    rm -f "$exp_bg" "$ctrl_bg"
    return 0
} 

# ============================= Peak Consensus =============================
# Usage: run_consensus <tool>
run_consensus() {
    local tool="$1"
    local peak_dir="$PEAK_DIR/$tool/peak"
    local plot_dir="$PEAK_DIR/$tool"

    # SEACR peak filenames carry the stringency (relaxed/stringent) from config;
    # prefer the file matching the current setting when several coexist.
    local stringency=""
    if [[ "$tool" == "seacr" ]]; then
        read -ra seacr_params_arr <<< "$SEACR_PARAMETER"
        stringency="${seacr_params_arr[2]:-stringent}"
    fi

    # Collect samples by target
    declare -A target_peaks
    declare -a all_peak_files
    local n_targets=0

    while IFS=, read -r sample group control target fq1 fq2 || [[ -n "${sample:-}" ]]; do
        [[ "$sample" == "sample" ]] && continue
        [[ -z "$sample" ]] && continue

        local peak_file
        peak_file=$(discover_peak_file "$tool" "$sample" "$peak_dir" "$stringency")
        [[ ! -f "$peak_file" ]] && continue

        all_peak_files+=("$peak_file")

        if [[ -n "$target" ]]; then
            if [[ -z "${target_peaks[$target]:-}" ]]; then
                target_peaks[$target]="$peak_file"
                n_targets=$((n_targets + 1))
            else
                target_peaks[$target]="${target_peaks[$target]} $peak_file"
            fi
        fi
    done < <(tail -n +2 "$SAMPLESHEET" | tr -d '\r')

    if [[ "$n_targets" -eq 0 ]]; then
        log_warn "[$tool] No usable peak files found for any target"
        log_warn "        (no control library and/or no peaks called); consensus skipped"
        return 0
    fi

    # Create consensus for each target
    for target in "${!target_peaks[@]}"; do
        local -a peaks=()
        read -ra peaks <<< "${target_peaks[$target]}"
        # echo "$target: ${peaks[@]}"

        if [[ ${#peaks[@]} -eq 0 ]]; then
            log_warn "No peak files for target: $target"
            continue
        fi

        local consensus_bed="${plot_dir}/consensus_${target}.bed"
        if [[ ! -s "$consensus_bed" ]]; then
            log_info "[$tool][$target] Make consensus from ${#peaks[@]} samples"
            # log_info "Samples: ${peaks[@]}"
            merge_peakfiles --input-peaks "${peaks[*]}" --output-bed "$consensus_bed" --chrom-size "$CHROM_SIZES" || \
                { 
                    log_warn "[$tool] Failed to create consensus for: $target"
                    continue
                }
        else 
            log_info "[$tool][$target] Consensus peak completed"
        fi
    done

    # Create consensus for all samples, only if N target > 1
    if [[ "$n_targets" -gt 1 ]] && [[ ! -s "${plot_dir}/consensus_all.bed" ]]; then
        local consensus_bed="${plot_dir}/consensus_all.bed"
        log_info "[$tool] Creating consensus peaks for: all (${#all_peak_files[@]} samples)"
        merge_peakfiles --input-peaks "${all_peak_files[*]}" --output-bed "$consensus_bed" --chrom-size "$CHROM_SIZES" || \
            log_warn "[$tool] Failed to create consensus for: all"
    fi
}



calculate_frip() {
    local prefix="$1"
    local consensus_bed="$2"
    local outdir="$3"
    shift 3

    local -a bam_array=("$@")
    if [[ ${#bam_array[@]} -eq 0 || ! -f "$consensus_bed" ]]; then
        return 0
    fi
    local -a name_array=()
    for bam in "${bam_array[@]}"; do
        name_array+=("$(basename "$bam" .filtered.bam)")
    done
    
    local frip_tab="$outdir/consensus_${prefix}_frip.tab"
    local frip_plot="$outdir/consensus_${prefix}_frip.pdf"
    if [[ ! -s "$frip_tab" ]]; then
        log_info "[QC] Computing FRiP: $prefix"
        plotEnrichment -p "$THREADS" -b "${bam_array[@]}" \
            --BED "$consensus_bed" --labels "${name_array[@]}" --outRawCounts "$frip_tab" --extendReads \
            --plotFile "$frip_plot" --plotTitle "FRiP - $prefix (Consensus Peaks)" >/dev/null
    fi
}

profile_heatmap() {
    local prefix="$1"
    local bed_file="$2"
    local type="$3"
    local outdir="$4"
    shift 4

    local -a bw_array=("$@")
    if [[ ${#bw_array[@]} -eq 0 || ! -f "$bed_file" ]]; then
        return 0
    fi
    local -a name_array=()
    for bw in "${bw_array[@]}"; do
        name_array+=("$(basename "$bw" .${NORM_METHOD}.bw)")
    done
        
    local bed_name=$(basename "$bed_file" .bed)
    log_info "[Heatmap QC] $prefix ($type) over $bed_name"
    
    # Subsample large BED files to bound matrix memory usage
    local region_count=$(wc -l < "$bed_file")
    local heatmap_bed="$bed_file"
    if [[ -n "$HEATMAP_MAX_REGIONS" && "$region_count" -gt "$HEATMAP_MAX_REGIONS" ]]; then
        log_warn "[Heatmap QC] $bed_name has $region_count regions, subsampling to $HEATMAP_MAX_REGIONS (fixed seed)"
        heatmap_bed="$outdir/${bed_name}_${prefix}_subsampled_${HEATMAP_MAX_REGIONS}.bed"
        if [[ ! -s "$heatmap_bed" ]]; then
            # deterministic subsample: 'yes' provides a reproducible random source
            shuf --random-source=<(yes | head -c 10000000) -n "$HEATMAP_MAX_REGIONS" "$bed_file" \
                | sort -k1,1 -k2,2n > "$heatmap_bed"
        fi
    fi
    
    # TSS heatmap
    if [[ "$type" == "tss" || "$type" == "both" ]]; then
        local heatmap_tss="$outdir/${bed_name}_${prefix}_tss_${NORM_METHOD}_heatmap.pdf"
        if [[ ! -s "$heatmap_tss" ]]; then
            local mat_tss="$outdir/${bed_name}_${prefix}_tss_${NORM_METHOD}_mat.gz"
            [[ ! -s "$mat_tss" ]] && \
                computeMatrix reference-point --referencePoint TSS -S "${bw_array[@]}" -R "$heatmap_bed" \
                    -o "$mat_tss" -p "$THREADS" -b 3000 -a 3000 --binSize "$HEATMAP_BINSIZE" --skipZeros \
                    --samplesLabel "${name_array[@]}" --quiet >/dev/null
            plotHeatmap -m "$mat_tss" -out "$heatmap_tss" --colorMap Blues >/dev/null
        fi
    fi

    # Center heatmap
    if [[ "$type" == "center" || "$type" == "both" ]]; then
        local heatmap_center="$outdir/${bed_name}_${prefix}_center_${NORM_METHOD}_heatmap.pdf"
        if [[ ! -s "$heatmap_center" ]]; then
            local mat_center="$outdir/${bed_name}_${prefix}_center_${NORM_METHOD}_mat.gz"
            [[ ! -s "$mat_center" ]] && \
                computeMatrix reference-point --referencePoint center -S "${bw_array[@]}" -R "$heatmap_bed" \
                    -o "$mat_center" -p "$THREADS" -b 3000 -a 3000 --binSize "$HEATMAP_BINSIZE" --skipZeros \
                    --samplesLabel "${name_array[@]}" --quiet >/dev/null
            plotHeatmap -m "$mat_center" -out "$heatmap_center" --colorMap Blues >/dev/null
        fi
    fi
    
    # # Gene body heatmap (unchanged: always generated)
    # local heatmap_body="$MULTIQC_DIR/${bed_name}_${prefix}_body_${NORM_METHOD}_heatmap.pdf"
    # if [[ ! -s "$heatmap_body" ]]; then
    #     local mat_body="$MULTIQC_DIR/${bed_name}_${prefix}_body_${NORM_METHOD}_mat.gz"
    #     [[ ! -s "$mat_body" ]] && \
    #         computeMatrix scale-regions -S "${bw_array[@]}" -R "$bed_file" \
    #             -o "$mat_body" -p "$THREADS" -b 3000 -a 3000 --binSize "$HEATMAP_BINSIZE" \
    #             --regionBodyLength 5000 --samplesLabel "${name_array[@]}" \
    #             --quiet 2>/dev/null
    #     plotHeatmap -m "$mat_body" -out "$heatmap_body" --colorMap Blues 2>/dev/null
    # fi
}

bam_qc() {
    local -a bam_array=("$@")
    
    if [[ ${#bam_array[@]} -eq 0 ]]; then
        return 0
    fi
    
    local -a name_array=()
    for bam in "${bam_array[@]}"; do
        name_array+=("$(basename "$bam" .filtered.bam)")
    done
    
    # Fragment length distribution
    if [[ ! -s "$MULTIQC_DIR/BAM_fragment_length.pdf" ]]; then
        log_info "[BAM QC] Calculating fragment length"
        bamPEFragmentSize -b "${bam_array[@]}" -p "$THREADS" --maxFragmentLength "$MAX_FRAG_LENGTH" \
            --histogram "$MULTIQC_DIR/BAM_fragment_length.pdf" --samplesLabel "${name_array[@]}" \
            --outRawFragmentLengths "$MULTIQC_DIR/BAM_fragment_length.txt" >/dev/null
    fi
    
    # Fingerprint
    if [[ ! -s "$MULTIQC_DIR/BAM_fingerprint.pdf" ]]; then
        log_info "[BAM QC] Generating fingerprint"
        plotFingerprint -b "${bam_array[@]}" -p "$THREADS" --labels "${name_array[@]}" --skipZeros \
            --plotFile "$MULTIQC_DIR/BAM_fingerprint.pdf" --outRawCounts "$MULTIQC_DIR/BAM_fingerprint.txt" >/dev/null 2>&1
    fi
}

bigwig_qc() {
    local prefix="$1"
    shift
    local -a bw_array=("$@")
    
    if [[ ${#bw_array[@]} -eq 0 ]]; then
        return 0
    fi
    
    local -a name_array=()
    for bw in "${bw_array[@]}"; do
        name_array+=("$(basename "$bw" .${NORM_METHOD}.bw)")
    done
    
    local npz_file="$MULTIQC_DIR/BigWig_${prefix}_${NORM_METHOD}.npz"
     
    # Compute summary
    if [[ ! -s "$npz_file" ]]; then
        log_info "[BigWig QC] Computing BigWig"
        multiBigwigSummary bins -b "${bw_array[@]}" -p "$THREADS" \
            --labels "${name_array[@]}" -o "$npz_file" 2>/dev/null
    fi
    
    # PCA plot
    if [[ ! -s "$MULTIQC_DIR/BigWig_${prefix}_${NORM_METHOD}_PCA.pdf" ]]; then
        log_info "[BigWig QC] Generating PCA"
        python "$SCRIPT_DIR/../scripts/plot_pca.py" -in "$npz_file" \
            -o "$MULTIQC_DIR/BigWig_${prefix}_${NORM_METHOD}_PCA.pdf" \
            --outFileNameData "$MULTIQC_DIR/BigWig_${prefix}_${NORM_METHOD}_PCA.tab" \
            --ntop "$PCA_NTOP" --plotTitle "$prefix" \
            --samplesheet "$SAMPLESHEET" >/dev/null 2>&1 || {
                log_warn "plot_pca.py failed, falling back to plotPCA"
                plotPCA -in "$npz_file" -o "$MULTIQC_DIR/BigWig_${prefix}_${NORM_METHOD}_PCA.pdf" >/dev/null
            }
    fi
    
    # Correlation heatmap
    if [[ ! -s "$MULTIQC_DIR/BigWig_${prefix}_${NORM_METHOD}_correlation.pdf" ]]; then
        log_info "[BigWig QC] Generating Correlation"
        plotCorrelation -in "$npz_file" --corMethod spearman --whatToPlot heatmap \
            -o "$MULTIQC_DIR/BigWig_${prefix}_${NORM_METHOD}_correlation.pdf" >/dev/null
    fi
}


run_global_qc() {
    # Collect all samples organized by target
    # Populates: TARGET_SAMPLES (associative array)
    # NOTE: `declare -g` does NOT clear already-global arrays, so reset them
    # explicitly; otherwise samples accumulate across prior peak-QC calls.
    declare -gA TARGET_SAMPLES=()
    declare -ga ALL_SAMPLES=() ALL_BAMS=() ALL_BWS=() ALL_TARGETS=()
    while IFS=, read -r sample group control target fq1 fq2 || [[ -n "${sample:-}" ]]; do
        [[ "$sample" == "sample" ]] && continue
        [[ -z "$sample" ]] && continue
        
        local bam="$ALIGN_DIR/${sample}.filtered.bam"
        local bw="$ALIGN_DIR/${sample}.${NORM_METHOD}.bw"
        
        [[ ! -f "$bam" ]] && continue
        
        ALL_SAMPLES+=("$sample")
        ALL_BAMS+=("$bam")
        ALL_BWS+=("$bw")
        
        if [[ -n "$target" ]]; then
            if [[ -z "${TARGET_SAMPLES[$target]:-}" ]]; then
                TARGET_SAMPLES[$target]="$sample"
                ALL_TARGETS+=("$target")
            else
                TARGET_SAMPLES[$target]="${TARGET_SAMPLES[$target]} $sample"
            fi
        fi
    done < <(tail -n +2 "$SAMPLESHEET" | tr -d '\r')
    
    if [[ ${#ALL_SAMPLES[@]} -eq 0 ]]; then
        log_warn "No samples found for QC"
        return 0
    fi
    
    log_info "Found ${#ALL_SAMPLES[@]} samples across ${#ALL_TARGETS[@]} targets"
    
    # BAM-level QC (all samples)
    bam_qc "${ALL_BAMS[@]}"
    
    # BigWig QC for all samples
    bigwig_qc "all_samples" "${ALL_BWS[@]}"
    
    # Heatmaps for all samples over genomic regions
    for bed_file in "${BED_REGIONS[@]}"; do
        [[ -f "$bed_file" ]] && profile_heatmap "all_samples" "$bed_file" "both" "$MULTIQC_DIR" "${ALL_BWS[@]}"
    done
    
    # MultiQC (non-peak QC stays in the multiqc/ directory)
    log_info "[Multi QC] Generating MultiQC report"
    multiqc "$OUTDIR" --force -o "$MULTIQC_DIR" --title "CUT&Tag Analysis" 2>/dev/null || true
}

# Per-tool peak QC: FRiP + heatmaps over this tool's consensus peaks,
# written directly under 04_peaks/<tool>/. The single MultiQC report is
# generated later in Phase 4 (run_global_qc), scanning the whole OUTDIR.
# Usage: run_peak_qc <tool>
run_peak_qc() {
    local tool="$1"
    local peak_dir="$PEAK_DIR/$tool/peak"
    local plot_dir="$PEAK_DIR/$tool"

    # Collect samples organized by target (same logic as run_global_qc)
    # NOTE: `declare -g` does NOT clear already-global arrays, so reset them
    # explicitly; otherwise samples accumulate across tool calls (duplicates).
    declare -gA TARGET_SAMPLES=()
    declare -ga ALL_SAMPLES=() ALL_BAMS=() ALL_BWS=() ALL_TARGETS=()
    while IFS=, read -r sample group control target fq1 fq2 || [[ -n "${sample:-}" ]]; do
        [[ "$sample" == "sample" ]] && continue
        [[ -z "$sample" ]] && continue
        
        local bam="$ALIGN_DIR/${sample}.filtered.bam"
        local bw="$ALIGN_DIR/${sample}.${NORM_METHOD}.bw"
        
        [[ ! -f "$bam" ]] && continue
        
        ALL_SAMPLES+=("$sample")
        ALL_BAMS+=("$bam")
        ALL_BWS+=("$bw")
        
        if [[ -n "$target" ]]; then
            if [[ -z "${TARGET_SAMPLES[$target]:-}" ]]; then
                TARGET_SAMPLES[$target]="$sample"
                ALL_TARGETS+=("$target")
            else
                TARGET_SAMPLES[$target]="${TARGET_SAMPLES[$target]} $sample"
            fi
        fi
    done < <(tail -n +2 "$SAMPLESHEET" | tr -d '\r')
    
    if [[ ${#ALL_SAMPLES[@]} -eq 0 ]]; then
        log_warn "[$tool] No samples found for peak QC"
        return 0
    fi
    
    # Consensus peak QC per target
    for target in "${ALL_TARGETS[@]}"; do
        local -a target_bams=() target_bws=()
        read -ra target_samples <<< "${TARGET_SAMPLES[$target]}"
        for sample in "${target_samples[@]}"; do
            target_bams+=("$ALIGN_DIR/${sample}.filtered.bam")
            target_bws+=("$ALIGN_DIR/${sample}.${NORM_METHOD}.bw")
        done

        local target_consensus="$plot_dir/consensus_${target}.bed"
        if [[ -f "$target_consensus" ]]; then
            calculate_frip "$target" "$target_consensus" "$plot_dir" "${target_bams[@]}"
            profile_heatmap "$target" "$target_consensus" "center" "$plot_dir" "${target_bws[@]}"
        fi
    done
    
    # All-samples consensus peak QC, only if >1 target
    if [[ ${#ALL_TARGETS[@]} -gt 1 ]]; then
        local all_consensus="$plot_dir/consensus_all.bed"
        if [[ -f "$all_consensus" ]]; then
            calculate_frip "all" "$all_consensus" "$plot_dir" "${ALL_BAMS[@]}"
        fi
    fi
}


# ============================= Main Pipeline =============================
main() {
    local config_file="${1:-}"

    # Defaults for optional keys (protect against unset under `set -u`;
    # applied before parse_yaml_config because it reads PEAK_CALLER)
    SKIP_PREPROCESS="${SKIP_PREPROCESS:-false}"
    PEAK_CALLER="${PEAK_CALLER:-}"
    RUN_SPIKE="${RUN_SPIKE:-false}"
    NORM_METHOD="${NORM_METHOD:-CPM}"
    MACS_PARAMETER="${MACS_PARAMETER:-}"
    SEACR_PARAMETER="${SEACR_PARAMETER:-}"
    SORT_MEM_LIMIT="${SORT_MEM_LIMIT:-8G}"
    MAX_FRAG_LENGTH="${MAX_FRAG_LENGTH:-2000}"
    THREADS="${THREADS:-8}"

    # Load configuration
    parse_yaml_config "$config_file"
    
    # Parse peak_caller into a normalized tool list (comma/space separated)
    PEAK_CALLERS=()
    if [[ -n "$PEAK_CALLER" && "$PEAK_CALLER" != "null" && "$PEAK_CALLER" != "~" ]]; then
        IFS=', ' read -ra _pc_arr <<< "$PEAK_CALLER"
        for _t in "${_pc_arr[@]}"; do
            [[ -z "$_t" ]] && continue
            case "$_t" in
                macs|macs2) PEAK_CALLERS+=("macs") ;;
                seacr)      PEAK_CALLERS+=("seacr") ;;
                *)          log_warn "Unknown peak caller '$_t' ignored (supported: macs, seacr)" ;;
            esac
        done
    fi
    
    # Defaults for heatmap options (if not set in config)
    HEATMAP_BINSIZE="${HEATMAP_BINSIZE:-50}"
    HEATMAP_MAX_REGIONS="${HEATMAP_MAX_REGIONS:-100000}"
    PCA_NTOP="${PCA_NTOP:-100000}"
    log_info "  Heatmap bin size: $HEATMAP_BINSIZE (max regions: $HEATMAP_MAX_REGIONS, PCA ntop: $PCA_NTOP)"
    
    # Check dependencies (peak-caller binaries are checked per-tool in Phase 3)
    require_commands fastqc fastp bowtie2 sambamba samtools deeptools bedtools multiqc

    # set path
    OUTDIR="$ROOT_DIR/$OUTDIR"
    FASTQ_DIR="$ROOT_DIR/$FASTQ_DIR"
    SAMPLESHEET="$ROOT_DIR/$SAMPLESHEET"

    # Setup logging: keep a copy of the original terminal stdout (fd3), then send
    # all output to the log file; the pipeline's own [date-time]-prefixed
    # messages are echoed to the terminal via fd3 (tool chatter stays in the
    # log only). log_* are redefined below to duplicate the message to both.
    exec 3>&1
    local log_file="$ROOT_DIR/pipeline.log"
    exec > >(cat >> "$log_file") 2>&1
    log_info() { echo "[$(date '+%Y-%m-%d %H:%M')] [INFO] $*" | tee /dev/stderr >&3; }
    log_warn() { echo "[$(date '+%Y-%m-%d %H:%M')] [WARN] $*" | tee /dev/stderr >&3; }
    log_error() { echo "[$(date '+%Y-%m-%d %H:%M')] [ERROR] $*" | tee /dev/stderr >&3; }
    
    log_info "============================================================"
    log_info "CUT&Tag Analysis Pipeline"
    log_info "============================================================"

    # Setup genome
    setup_genome "$SPECIES" "$INDEX_ROOTDIR"

    # Append custom BED regions (bed_region key in config.yml)
    if [[ ${#CUSTOM_BED_REGIONS[@]} -gt 0 ]]; then
        log_info "Adding ${#CUSTOM_BED_REGIONS[@]} custom BED region(s) to heatmap QC"
        BED_REGIONS+=("${CUSTOM_BED_REGIONS[@]}")
    fi

    # Check samplesheet
    if [[ ! -s "$SAMPLESHEET" ]]; then
        log_warn "Samplesheet not found: $SAMPLESHEET"
        log_info "Generating template samplesheet from FASTQ directory..."
        generate_samplesheet "$FASTQ_DIR" "$SAMPLESHEET"
        log_info "Please edit $SAMPLESHEET and re-run the pipeline"
        exit 0
    fi

    # Define directory paths
    FASTQC_DIR="$OUTDIR/01_fastqc"
    FASTP_DIR="$OUTDIR/02_fastp"
    ALIGN_DIR="$OUTDIR/03_bam"
    PEAK_DIR="$OUTDIR/04_peaks"
    MULTIQC_DIR="$OUTDIR/multiqc"

    # Create directories
    create_dirs "$OUTDIR"
    
    # Initialize statistics file
    STATS_CSV="$OUTDIR/statistics_${NORM_METHOD}.csv"
    if [[ ! -f "$STATS_CSV" ]]; then
        log_info "Initializing statistics file: $STATS_CSV"
        cat > "$STATS_CSV" <<EOF
sample,group,control,target,fq1,fq2,total_reads,mapped_reads,duplicate_reads,filtered_reads,spike_reads,norm_method,scale_factor
EOF
    fi

    # Display configuration
    log_info "Configuration:"
    log_info "  Species: $SPECIES"
    log_info "  Samplesheet: $SAMPLESHEET"
    log_info "  Threads: $THREADS"
    log_info "  Normalization: $NORM_METHOD"
    log_info "  Peak calling: ${PEAK_CALLER:-none}"
    log_info "  Spike-in: $RUN_SPIKE"
    log_info "============================================================"
    
    # Phase 1: Pre-processing
    if [[ "$SKIP_PREPROCESS" == true ]]; then
        log_info ""
        log_info "========== Skip Pre-processing =========="
    else
        log_info ""
        log_info "========== Phase 1: Pre-processing  =========="
        create_dirs "$FASTQC_DIR" "$FASTP_DIR"
        loop_over_csv "$SAMPLESHEET" run_preprocess
    fi

    # Phase 2: Alignment
    log_info ""
    log_info "========== Phase 2: Alignment =========="
    create_dirs "$ALIGN_DIR"
    loop_over_csv "$SAMPLESHEET" run_alignment
    
    # Phase 3: Peak Calling (per selected tool)
    if [[ ${#PEAK_CALLERS[@]} -gt 0 ]]; then
        create_dirs "$PEAK_DIR"
        for tool in "${PEAK_CALLERS[@]}"; do
            TOOL_PEAK_DIR="$PEAK_DIR/$tool/peak"
            TOOL_PLOT_DIR="$PEAK_DIR/$tool"
            create_dirs "$TOOL_PEAK_DIR" "$TOOL_PLOT_DIR"
            
            case "$tool" in
                macs)   require_commands macs3 ;;
                seacr)  require_commands SEACR_1.3.sh ;;
            esac
            
            log_info ""
            log_info "========== Phase 3: Peak Calling ($tool) =========="
            loop_over_csv "$SAMPLESHEET" "run_${tool}"
            
            log_info "========== Consensus Peaks ($tool) =========="
            run_consensus "$tool"
            
            log_info "========== Peak QC ($tool) =========="
            run_peak_qc "$tool"
        done
    fi
    
    # Phase 4: QC
    log_info ""
    log_info "========== Phase 4: QC =========="
    create_dirs "$MULTIQC_DIR"
    run_global_qc
    
    log_info ""
    log_info "============================================================"
    log_info "Pipeline completed successfully!"
    log_info "============================================================"
}


# ============================= Entry Point =============================
main "$@"
